CREATE TABLE IF NOT EXISTS users
(
    id    BIGSERIAL PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    email VARCHAR(254) NOT NULL ,
    password VARCHAR(254)  NOT NULL
);

CREATE TABLE IF NOT EXISTS experiences
(
    id    BIGSERIAL PRIMARY KEY ,
    mindfulness  DOUBLE PRECISION NOT NULL ,
    attitudes  DOUBLE PRECISION NOT NULL ,
    selfRegulation  DOUBLE PRECISION NOT NULL ,
    empathy  DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS testresult
(
    id    BIGSERIAL PRIMARY KEY ,
    mindfulness  DOUBLE PRECISION NOT NULL ,
    attitudes  DOUBLE PRECISION NOT NULL ,
    selfRegulation  DOUBLE PRECISION NOT NULL ,
    empathy  DOUBLE PRECISION NOT NULL
);
