server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://85.192.34.28:3306/MySQL-3210?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: MgQwNFeTUdN8i84T

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:mysql://85.192.34.28:3306/MySQL-3210?serverTimezone=UTC
    user: user
    password: MgQwNFeTUdN8i84T

#  jwt:
#    token:
#      secret: jwtappdemo
#      expired: 3600000