server:
  port: 8080
  tomcat.uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:postgresql://185.86.145.179:5432/PostgreSQL-7801?current=schema_equp
    username: equp
    password: 5aKfpGNNswxHXmsg
    driver-class-name: org.postgresql.Driver
    initialization-mode: ALWAYS
    schema: classpath*:database/initDB.sql
#    data: classpath*:database/populateDB.sql


  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

