server:
  port: 8080
  tomcat.uri-encoding: utf-8
#
#spring:
#   datasource:
#     url: jdbc:mysql://85.192.34.102:3306/MySQL-7923?serverTimezone=UTC
#     driver-class-name: com.mysql.jdbc.Driver
#     username: userequp
#     password: kubNBeiS5hxMovoB